<a href="https://colab.research.google.com/github/SoniaSrivastava/Natural_Language_Processing/blob/main/TensorsDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# Zero Dimension tensor
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# One Dimension tensor
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
# Two Dimension tensor
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
# Three Dimension tensor
tensor_three_d = tf.constant(
[[[1,2,0],
  [3,5,-1]],
 [[10,2,0],
  [1,0,2]],
 [[5,8,0],
  [2,7,0]],
 [[2,1,9],
  [4,-3,32]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
# Finding shape of the tensor
tensor_three_d.shape

TensorShape([4, 2, 3])

In [ ]:
# Finding dimension of the tensor
tensor_three_d.ndim

3

In [ ]:
tensor_one_d_type = tf.constant([2,0,-3], dtype=tf.float32)
print(tensor_one_d_type)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [ ]:
# casting of tensor from one data type to another - in this example from float32 to int64
casted_tensor_one_d_type = tf.cast(tensor_one_d_type, dtype=tf.int64)
print(casted_tensor_one_d_type)


tf.Tensor([ 2  0 -3], shape=(3,), dtype=int64)


In [ ]:
# casting of tensor from one data type to another - in this example from float32 to int64
casted_tensor_one_d_type_1 = tf.cast(tensor_one_d_type, dtype=tf.bool)
print(casted_tensor_one_d_type_1)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
# Boolean tensor
tensor_bool = tf.constant([True, False, True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
# String Tensor
tensor_string = tf.constant("Hello World!")
print(tensor_string)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [ ]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
# Identity matrix tensor
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = None,
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
# Set Batch shape
# Identity matrix tensor
eye_tensor_batch = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = [3,],
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor_batch)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
# fill method - fill tensor with scalar values
fill_tensor = tf.fill([3,4], 5, name=None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
# ones method - fill tensor with 'one' values
ones_tensor = tf.ones([5,3])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
# creates a tensor of all ones that has the same shape as the input
ones_like_tensor = tf.ones_like(ones_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
# creates a tensor of all zeros
zeros_tensor = tf.zeros([3,4])
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
# shape method of tensor
print(tf.shape(zeros_tensor))

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [ ]:
# returns the rank of tensor
print(tf.rank(zeros_tensor))

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# returns the size of tensor
print(tf.size(zeros_tensor))

tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
# return random values tensor that has normal distribution
random_normal_tensor = tf.random.normal(
    [4,5],
    mean = 0,
    stddev = 1
    )
print(random_normal_tensor)

tf.Tensor(
[[-0.81490165 -0.00949798  1.2490461  -1.1624625   1.5918456 ]
 [-1.4386262   1.2484709   1.8905429  -0.40926474 -0.0116438 ]
 [ 0.9283654  -0.86199045  0.00930318 -1.8010933  -0.5006558 ]
 [ 0.5223751   2.2209046   1.0000424   0.56718576  0.16502164]], shape=(4, 5), dtype=float32)


In [ ]:
# return random values tensor that has uniform distribution
tf.random.set_seed(5)
random_uniform_tensor = tf.random.uniform(
    [4,5],
    minval = 0,
    maxval = 100,
    dtype = tf.int32,
    seed = 10
    )
print(random_uniform_tensor)

tf.Tensor(
[[39  3 16 83 45]
 [86 62 28 31  8]
 [89  6 80 36 12]
 [39 58 40 14  4]], shape=(4, 5), dtype=int32)


In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:6:2])
print(tensor_indexed[1:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [ ]:
# Two Dimension tensor
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
#print(tensor_two_d)
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
print(tensor_two_d[0:3, :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
print(tensor_two_d[2, :])

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [ ]:
print(tensor_two_d[:, 0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
print(tensor_two_d[..., 0])

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
# Three Dimension tensor
tensor_three_d = tf.constant(
[[[1,2,0],
  [3,5,-1]],
 [[10,2,0],
  [1,0,2]],
 [[5,8,0],
  [2,7,0]],
 [[2,1,9],
  [4,-3,32]]])
print(tensor_three_d[0, :, :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
# ... (three dots) indicates all
print(tensor_three_d[0, ..., :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
# math functions
x_abs = tf.constant([-2.5, 3.5])
print(tf.abs(x_abs))

tf.Tensor([2.5 3.5], shape=(2,), dtype=float32)


In [ ]:
# math functions - complex numbers
x_complex = tf.constant([[-2.25+4.75j], [-3.25+5.75j]])
print(tf.abs(x_complex))

tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


In [ ]:
print(tf.sqrt((-2.25)**2 + 4.75**2))

tf.Tensor(5.255949, shape=(), dtype=float32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)
x_3 = tf.add(x_1, x_2)
#x_3 = x_1 + x_2
print(x_3)

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)
x_3 = tf.multiply(x_1, x_2)
print(x_3)

tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)
x_3 = tf.subtract(x_1, x_2)
print(x_3)

tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.int32)
x_3 = tf.divide(x_1, x_2)
print(x_3)

tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7,6,0,6,7,11], dtype=tf.int32)
x_3 = tf.math.divide_no_nan(x_1, x_2)
print(x_3)

tf.Tensor([0.71428571 0.5        0.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2 = tf.constant([7], dtype=tf.int32)
x_3 = tf.add(x_1, x_2)
print(x_3)

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
a = tf.constant([1.0, 3.0, 5.0])
b = tf.constant([2.0, 2.0, 6.0])

# Element-wise minimum
min_result = tf.math.minimum(a, b)

# Element-wise maximum
max_result = tf.math.maximum(a, b)
print(min_result)
print(max_result)

tf.Tensor([1. 2. 5.], shape=(3,), dtype=float32)
tf.Tensor([2. 3. 6.], shape=(3,), dtype=float32)


In [ ]:
# math.argmax - returns index/position of the maximum value in each row below
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                       [3, 11, 16, 1, 8],
                       [14, 45, 23, 5, 27]])
print(tf.math.argmax(x_argmax))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [ ]:
x1_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x1_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
# math.argmin - returns index/position of the minimum value in each row below
x2_argmin = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmin(x2_argmin))

tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
# power
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
print(tf.pow(x,y))

tf.Tensor(
[[  256 65536]
 [    9    27]], shape=(2, 2), dtype=int32)


In [ ]:
# tf.math.reduce_sum - computes the sum of elements across dimensions of a tensor
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

# Sums all the elements of tensor
print(tf.math.reduce_sum(tensor_two_d))


tf.Tensor(35, shape=(), dtype=int32)


In [ ]:
print(tf.math.reduce_max(tensor_two_d))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
print(tf.math.reduce_min(tensor_two_d))

tf.Tensor(-1, shape=(), dtype=int32)


In [ ]:
print(tf.math.reduce_sum(tensor_two_d, axis = 0))

tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)


In [ ]:
print(tf.math.reduce_sum(tensor_two_d, axis = 1))

tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


In [ ]:
print(tf.math.reduce_mean(tensor_two_d, axis = 1))

tf.Tensor([1 2 4 4], shape=(4,), dtype=int32)


In [ ]:
tensor_2d_casted = tf.cast(tensor_two_d, dtype=tf.float16)
print(tf.math.reduce_std(tensor_2d_casted, axis = 1, keepdims=False))

tf.Tensor([0.8164 2.494  2.16   2.625 ], shape=(4,), dtype=float16)


In [ ]:
print(tf.math.top_k(tensor_two_d, k=1))

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)


In [ ]:
# top 2 largest numbers in each row and their corresponding indices
print(tf.math.top_k(tensor_two_d, k=2))

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 1],
       [5, 3],
       [6, 5],
       [8, 3]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]], dtype=int32)>)


In [ ]:
# Linear Algebra operations
# Matrix multiplication -> tf.linalg.matmul
x_1 = tf.constant([[2, 2], [3, 3]])
y_1 = tf.constant([[8, 16], [2, 3]])
print(tf.linalg.matmul(x_1,y_1))

tf.Tensor(
[[20 38]
 [30 57]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix multiplication
print(x_1@y_1)

tf.Tensor(
[[20 38]
 [30 57]], shape=(2, 2), dtype=int32)


In [ ]:
# Transpose of matrix
print(tf.transpose(x_1))

tf.Tensor(
[[2 3]
 [2 3]], shape=(2, 2), dtype=int32)


In [ ]:
# Sparse Tensors


In [ ]:
# tf.linalg.band_part